language: python

addons:
  postgresql: "9.4"
  firefox: "45.0"

dist: trusty

services:
  - postgresql
  - redis-server

matrix:
    include:
        - python: 3.5
          env:
          - PYTHON_VERSION=python3.5
          - TOXENV=py35

# http://stackoverflow.com/a/19460794/315168
cache:
  directories:
    # /home/travis/.cache/pip/wheels is the normal pip cache folder
    - $HOME/.cache/pip
    - .tox
    - geth
    - $HOME/.ethash

install:
  - travis_retry pip install tox

before_script:
# https://docs.travis-ci.com/user/gui-and-headless-browsers/
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - tar -xjf /tmp/firefox-45.0.tar.bz2 --directory /tmp
  - travis_retry sudo apt-get install software-properties-common -y -qq
  - travis_retry sudo add-apt-repository -y ppa:ethereum/ethereum
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install geth -y -qq
  - export PATH="/tmp/firefox:$PATH"
  - echo "Using firefox version `firefox --version`"
  - echo "Using geth `geth --help`"
  - psql -c 'create database wallet_test;' -U postgres
  - pip install -U pip

script:
  # https://pypi.python.org/pypi/coverage_enable_subprocess
  - pip install coverage-enable-subprocess
  - export COVERAGE_PROCESS_START=$PWD/.coveragerc
  - tox -- -x

after_success:
  # Update coverage information in codecov.io.
  - .tox/py35/bin/codecov
  # Dump package list so we have a log of last known good version set
  # This will simply fail under py34.
  - .tox/py35/bin/pip freeze

